### ISSUE TITLE
How do I include the visitor badge in my readme?

### ISSUE THREAD

**Issue by ApurvShah007** [jwenjian/visitor-badge#1]

**Comment by ApurvShah007** [comment]
Your visitor count is down too, is there any fix?

**Comment by jwenjian** [comment]
Now the service is under free version of glitch，so it will down if too many requests in the same time, I currently have no credit card to upgrade to a pro version 

You can 

1. fork it under your own account and deploy it let it works just for yourself 

2. Use Hits instead

Sorry for the inconvenience
