### ISSUE TITLE
Label and color

### ISSUE THREAD

**Issue by YuvrajRaghuvanshiS** [jwenjian/visitor-badge#10]
Hey, thanks for making this.
How can I change color, label etc?

**Comment by jwenjian** [comment]
I use default style of [google/pybadges](https://github.com/google/pybadges) to generate the svg, you can fork this project and change the code in [L59](https://github.com/jwenjian/visitor-badge/blob/master/main.py#L59), detail parameter can be referenced [here](https://github.com/google/pybadges#library-usage)

For example, change color of right text to 'red' like this:

```python
svg = badge(left_text="visitors", right_text=str(latest_count), rightc_color='red')
```

**Comment by jwenjian** [comment]
left text is now can be customized, see -> https://github.com/jwenjian/visitor-badge/releases/tag/v1.0.2

I will close this issue now.

:)

**Comment by YuvrajRaghuvanshiS** [comment]
Thanks for the updates.
