### ISSUE TITLE
Add New Server page-views.glitch.com

### ISSUE THREAD

**Issue by HariKishorePec** [jwenjian/visitor-badge#11]
Loved you work. Indeed nice work, Thanks for that. Please verify credibility and you might add it your Readme page to split the loads.

Please have a look at it. Minor changes in API calls and endpoints.

**Comment by jwenjian** [comment]
Thanks for the contribution, I have added into the README page.

**Comment by HariKishorePec** [comment]
Thanks. for viewers, for reference, https://page-views.glitch.me/
