### ISSUE TITLE
visitor-badge is down

### ISSUE THREAD

**Issue by xiaoluoboding** [jwenjian/visitor-badge#2]
This project has received too many requests, please try again later. 😂

**Comment by jwenjian** [comment]
See README.

<img width="873" alt="截屏2020-07-16 上午12 30 53" src="https://user-images.githubusercontent.com/25657798/87570720-9f4dfa00-c6fb-11ea-9d04-1a28a055f92d.png">

**Comment by jwenjian** [comment]
I will let this issue opened because there must be many users came along here for the same issue :-(

**Comment by hehuapei** [comment]
已fork！需要的小伙伴可以用把域名替换成 https://visitor-badge.laobi.icu使用！

**Comment by jwenjian** [comment]
> 已fork！需要的小伙伴可以用把域名替换成 https://visitor-badge.laobi.icu 使用！

你还需要把 .env 文件中的 `md5_key` 的值换成 `guess_what`， 这样之前用户的数量才会保留下来，否则就会从1开始

**Comment by hehuapei** [comment]
> > 已fork！需要的小伙伴可以用把域名替换成 https://visitor-badge.laobi.icu 使用！
> 
> 你还需要把 .env 文件中的 `md5_key` 的值换成 `guess_what`， 这样之前用户的数量才会保留下来，否则就会从1开始

现在暂时都是从1开始哈！感觉那个计数接口有时不灵，我自己实现了一个，所以只能从新计算

**Comment by jwenjian** [comment]
> > > 已fork！需要的小伙伴可以用把域名替换成 https://visitor-badge.laobi.icu 使用！
> > 
> > 
> > 你还需要把 .env 文件中的 `md5_key` 的值换成 `guess_what`， 这样之前用户的数量才会保留下来，否则就会从1开始
> 
> 现在暂时都是从1开始哈！感觉那个计数接口有时不灵，我自己实现了一个，所以只能重新计算

嗯 估计是网络问题

**Comment by xiaoluoboding** [comment]
@jwenjian I deploy myself successful, thanks.

**Comment by Nathan13888** [comment]
https://visitor-badge.laobi.icu still starts counting from one.

**Comment by Nathan13888** [comment]
@jwenjian Do you think it is possible to host this app on Heroku or on a free GCP F1-Micro server??

Heroku provides 1000 hours of dyno service per month which is enough to host ~1.3 "dynos" (apps) 24 hours a day. Btw, the "free" dyno goes to sleep ~30 minutes so ping it using curl to keep it awake that way it would not go to sleep.

**Comment by hehuapei** [comment]
> https://visitor-badge.laobi.icu still starts counting from one.

you can try agan! i restored the  count-api

**Comment by Nathan13888** [comment]
Awesome. Looks good now! Thanks.

**Comment by jwenjian** [comment]
> @jwenjian Do you think it is possible to host this app on Heroku or on a free GCP F1-Micro server??
> 
> Heroku provides 1000 hours of dyno service per month which is enough to host ~1.3 "dynos" (apps) 24 hours a day. Btw, the "free" dyno goes to sleep ~30 minutes so ping it using curl to keep it awake that way it would not go to sleep.

Yes, If you have a 1000 hours per month, then the Heroku is a good choice than glitch free version, it's good, feel free to give a try.

**Comment by Nathan13888** [comment]
@jwenjian I think it might be worth the effort in the future to move away from glitch to use heroku if you want to avoid sleeping but I guess it's your decision. ;'')
