### ISSUE TITLE
SS-1: View Counter API down

### ISSUE THREAD

**Issue by Sulstice** [jwenjian/visitor-badge#25]
Hello, the view counter api went down and I'm wondering if I can do anything to help fix it?

**Comment by warriorwizard** [comment]
it is such a great api 
please restore it🙏🙏

**Comment by jwenjian** [comment]
Hi, I am using a [free count API](https://countapi.xyz) to store the count ，seems the API does not work, investigating...

**Comment by jwenjian** [comment]
It should back to normal now, but I didnt do anything yet actually 👉👈
