### ISSUE TITLE
[⚡FEATURE-REQUEST] Add badge for library downloads.

### ISSUE THREAD

**Issue by ErrorxCode** [jwenjian/visitor-badge#26]
### Just like [jitpack](https://jitpack.io/#ErrorxCode/EasyInsta) which shows the download count of our library, can you please add the same badge so that it can be directly demonstrated in GitHub readme.

**Comment by jwenjian** [comment]
Hi, I think this PR is helpful for you:  https://github.com/jitpack/jitpack.io/issues/837 

Also see this issue: https://github.com/jitpack/jitpack.io/issues/2092 

This repo is for badge to count page views, so sorry, this feature will not be included :(

Hope above links helps.

BR,

**Comment by ErrorxCode** [comment]
> Hi, I think this PR is helpful for you: [jitpack/jitpack.io#837](https://github.com/jitpack/jitpack.io/issues/837)
> 
> Also see this issue: [jitpack/jitpack.io#2092](https://github.com/jitpack/jitpack.io/issues/2092)
> 
> This repo is for badge to count page views, so sorry, this feature will not be included :(
> 
> Hope above links helps.
> 
> BR,

Thnx for the links, but I want the total download count. It's about per week or per month. Any other idea?

**Comment by ErrorxCode** [comment]
Ya okay. Besides this, your view counter badge does not show the real views (that is shown in traffic tab). It shows the views as the count of the opening page, even if the same user refreshes the page, the count increases.

**Comment by jwenjian** [comment]
yes，its caused by limitation of github camo image proxy server , I have no information about the visitor ,just know the page was opened
