### ISSUE TITLE
how to deploy under my own glitch account 

### ISSUE THREAD

**Issue by ran-huang** [jwenjian/visitor-badge#29]
Could you please provide a simple guide on deploying this under glitch? Thanks!

**Comment by jacobsayono** [comment]
following this issue; please show a tutorial! do we use vercel?

**Comment by ledges** [comment]
> following this issue; please show a tutorial! do we use vercel?

Use my own program; it is simpler and has support for only requests from the camo.githubusercontent.com domain. So users can't spam bot requests and completely destroy your server: 

[GitHub Profile View Counter](https://replit.com/@beliefs/github-profile-counter?v=1) just fork this :)

**Comment by jwenjian** [comment]
Steps:

1. fork the project to your github account, e.g. https://github.com/bob/visitor-badge
2. sign in glitch with your github account and go to glitch dashboard
3. click 'new project' in the top right corner then choose "import from Github"
4. input url to your forked project, e.g. https://github.com/bob/visitor-badge.git
5. just follow the process to deploy, it should be ok

Closing this issue now, please try and if any questions, leave comment ;)
