### ISSUE TITLE
what is meaning of app sleeps?

### ISSUE THREAD

**Issue by anirudhakulkarni** [jwenjian/visitor-badge#3]
The glitch site mentioned it sleeps after 5 mins of inactivity. Does this mean my visitor count stops? or the counter restarts?
I have forked the project and created another app on glitch. But still unaware of meaning of it sleeps.

**Comment by Nathan13888** [comment]
im pretty sure that it just takes some time for the glitch app to startup but it still counts it

**Comment by jwenjian** [comment]
> im pretty sure that it just takes some time for the glitch app to startup but it still counts it

Yes you are right，after the sleep, the count will start working.
