### ISSUE TITLE
A new counter and badge generate services

### ISSUE THREAD

**Issue by plantree** [jwenjian/visitor-badge#30]
Hi @jwenjian,

I also came across **the problem with access limitations**, and I also found that **lack of control over data**. 

Therefore, I wrote another counter service and badge generator service, which could help manage data better. 

Relative documentation could be found here: [https://plantree.github.io/project-docs/counter/usage.html](https://plantree.github.io/project-docs/counter/usage.html)。

Hope to provide an alternative solution for users facing similar problems.

Any suggestion will help me further improve these services and I'll appreciate.

**Comment by jwenjian** [comment]
Looks great ;) 

Are you manage the server / data by your self or using some SaaS?

**Comment by plantree** [comment]
Yes. 

The counter service is deployed in Azure and uses Vercel as Edge Middleware. The badge generator service is simple and deployed in Vercel directly.

Currently the services are **basically available**, and the next step is **mainly to improve availability and latency**.

**Comment by jwenjian** [comment]
Readme updated
