### ISSUE TITLE
Visitor badge is not working ....

### ISSUE THREAD

**Issue by hegdepavankumar** [jwenjian/visitor-badge#33]
The visitor badge is not working...    
https://camo.githubusercontent.com/8abd5a378ce3d4a589c3484d8fdb421ef1c20caa384be3946595eb9468050244/68747470733a2f2f76697369746f722d62616467652e676c697463682e6d652f62616467653f706167655f69643d6865676465706176616e6b756d6172

showing error

**Comment by LucasColas** [comment]
The service seems to be down now.

**Comment by hegdepavankumar** [comment]
> 
okay!...
